[ADD] stock_move_line_multi_company_security: New module
OCA/multi-company pull request #114
Opened 2018-11-13 15:34 UTC by chienandalu

In a multi-company enviroment, a user can access to all the companies product
movements from the product form *Product Moves* stat button. That's a full
disclosure of the companies operations wich is a sensible information that
gives accurate clues about what they sell, purchase or move internally.

This module adds the proper security to avoid it.

cc @Tecnativa

2018-11-15 10:10 UTC, chienandalu commented
Tests seem to be failing on `base_multicompany`

2018-11-15 10:11 UTC, pedrobaeza commented
Does it happen on main branch?

2018-11-15 10:13 UTC, chienandalu commented
It seems so: https://travis-ci.org/OCA/multi-company/jobs/440710190#L1374

2018-11-15 10:18 UTC, pedrobaeza commented
OK, I'll check

2018-11-16 00:31 UTC, pedrobaeza requested changes

2018-11-16 00:31 UTC, pedrobaeza commented on stock_move_line_multi_company_security/README.rst
> +movements from the product form *Product Moves* stat button. That's a full
`movements`? Isn't better `moves`?

2018-11-16 00:31 UTC, pedrobaeza commented on stock_move_line_multi_company_security/README.rst
> +disclosure of the companies operations wich is a sensible information that
s/wich/which

2018-11-16 00:31 UTC, pedrobaeza commented on stock_move_line_multi_company_security/README.rst
> +disclosure of the companies operations wich is a sensible information that
s/a sensible/sensitive (false friend and remove the a)

2018-11-16 00:31 UTC, pedrobaeza commented on stock_move_line_multi_company_security/README.rst
> +  merged: https://github.com/odoo/odoo/pull/28575
s/merged/gets merged

2018-11-16 00:31 UTC, pedrobaeza commented on stock_move_line_multi_company_security/__manifest__.py
> +# Copyright 2018 Tecnativa S.L. - David Vidal
No need of the `S.L.` part

2018-11-16 00:31 UTC, pedrobaeza commented on stock_move_line_multi_company_security/security/stock_security.xml
> +<odoo noupdate="0">
Better to put it noupdate="1" as the rest of security rules in Odoo.

2018-11-16 00:31 UTC, pedrobaeza commented on stock_move_line_multi_company_security/tests/test_stock_move_line_multi_company_security.py
> +        super(TestStockMoveLineMultiCompany, cls).setUpClass()
Well, you are here testing security rules, not the module itself, but well, as you have already developed them, it's good to have it to see if other module changes this.

2018-11-16 00:40 UTC, pedrobaeza commented
I have fixed the error in main branch

2018-11-20 11:08 UTC, chienandalu commented
@pedrobaeza Can you review again?

2019-01-23 18:41 UTC, pedrobaeza requested changes

2019-01-23 18:41 UTC, pedrobaeza commented on stock_move_line_multi_company_security/README.rst
> +#. Log in with a company belonging to a company.
First `company` word should be `user`

2019-01-23 18:41 UTC, pedrobaeza commented on stock_move_line_multi_company_security/README.rst
> +* It's expected to have this security issue solved in Odoo 13 when this issue
s/issue/pull request

2019-01-23 18:41 UTC, pedrobaeza commented on stock_move_line_multi_company_security/README.rst
> +Usage
Add installation instructions saying that this creates and fill a new column in stock.move.line, so it might take a bit.

2019-01-23 18:41 UTC, pedrobaeza commented on stock_move_line_multi_company_security/README.rst
> +Usage
And maybe a pre-init hook adding the column and performing an SQL update is also advisable.

2019-03-07 09:48 UTC, LoisRForgeFlow approved these changes
It makes sense, code review LGTM :+1:

2019-03-07 12:06 UTC, pedrobaeza approved these changes

2019-03-07 12:06 UTC, merged