ADD sale_layout_multi_company
OCA/multi-company pull request #28
Opened 2016-09-16 15:20 UTC by eLBati

This module extends the functionality of sale_layout module adding support for multi company

2016-09-16 15:24 UTC, pedrobaeza commented on sale_layout_multi_company/README.rst
> +Known issues / Roadmap
Remove this empty section

2016-09-16 15:24 UTC, pedrobaeza commented on sale_layout_multi_company/__openerp__.py
> +    "category": "Sale",
Sales Management

2016-09-16 15:25 UTC, pedrobaeza requested changes

2016-09-16 15:31 UTC, eLBati commented on sale_layout_multi_company/README.rst
> +Known issues / Roadmap
done

2016-09-16 15:31 UTC, eLBati commented on sale_layout_multi_company/__openerp__.py
> +    "category": "Sale",
done

2016-09-16 15:33 UTC, pedrobaeza approved these changes

2016-09-16 15:34 UTC, pedrobaeza commented
When CIs goes green :+1:

2016-09-22 08:06 UTC, archetipo commented
:+1:

2017-01-17 09:38 UTC, eLBati commented
merge?

2017-08-17 00:11 UTC, merged