[9.0][MIG] inter_company_rules: Migrate v8.0 to v9.0
OCA/multi-company pull request #30
Opened 2016-11-17 01:24 UTC by carlosdauden

Based in https://github.com/OCA/multi-company/pull/13

@Tecnativa

2016-11-18 11:45 UTC, cubells commented on inter_company_rules/README.rst
> +
Can you follow this template?
https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2016-11-18 11:47 UTC, cubells commented on inter_company_rules/__openerp__.py
> +##############################################################################
Follow this template for header fields:
https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py

2016-11-18 12:13 UTC, cubells commented on inter_company_rules/models/purchase_order.py
> +        # read it as sudo, because inter-compagny user
Typo here

2016-11-18 12:13 UTC, cubells commented on inter_company_rules/models/sale_order.py
> +        # because inter-compagny user can not have the access right on PO
Type here

2016-11-22 08:39 UTC, pedrobaeza commented
You have to rename the module to singular.

2016-11-22 09:00 UTC, pedrobaeza requested changes

2016-11-22 09:00 UTC, pedrobaeza commented on inter_company_rules/README.rst
> +This module is usefull if there are multiple companies in the same Odoo database and those companies sell goods or services among themselves.
s/usefull/useful

2016-11-22 09:00 UTC, pedrobaeza commented on inter_company_rules/README.rst
> +This module is usefull if there are multiple companies in the same Odoo database and those companies sell goods or services among themselves.
Introduce here line breaks for respecting 80 cols limit

2016-11-22 09:00 UTC, pedrobaeza commented on inter_company_rules/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/133/8.0
s/8.0/9.0

2016-11-22 09:00 UTC, pedrobaeza commented on inter_company_rules/README.rst
> +* Lorenzo Battistini <lorenzo.battistini@agilebg.com>
Put yourself here

2016-11-22 09:00 UTC, pedrobaeza commented on inter_company_rules/__openerp__.py
> +    'author': 'Odoo SA, Odoo Community Association (OCA)',
Include our company here.

2016-11-22 09:00 UTC, pedrobaeza commented on inter_company_rules/models/account_invoice.py
> +                    invoice.inter_company_create_invoice(company,
Better to use another indentation style to save lines.

2016-11-22 09:00 UTC, pedrobaeza commented on inter_company_rules/models/account_invoice.py
> +from openerp.exceptions import Warning as UserError
In v9 now `UserError` is the main exception

2016-11-22 09:00 UTC, pedrobaeza commented on inter_company_rules/models/account_invoice.py
> +        vals = {
Better to call the corresponding onchange method. The only concern here is if it will be correctly called in multi-company context.

2016-11-22 09:00 UTC, pedrobaeza commented on inter_company_rules/models/purchase_order.py
> +        intercompany_uid = (company.intercompany_user_id and
This can be simplify in this version: `intercompany_uid = company.intercompany_user_id.id`

2016-11-22 09:00 UTC, pedrobaeza commented on inter_company_rules/test/test_intercompany_data.yml
> +-
Change tests to Python.

2016-11-22 10:24 UTC, chafique-delli commented
hi, @carlosdauden 
Note that the 'inter_company_rules' module (https://github.com/OCA/multi-company/pull/13) has been splitted in two modules(purchase_sale_inter_company and account_invoice_inter_company).
View PR for purchase_sale_inter_company: https://github.com/OCA/multi-company/pull/31
View PR for account_invoice_inter_company: https://github.com/OCA/multi-company/pull/32

2016-11-22 10:28 UTC, pedrobaeza commented
What is the advantage of splitting them?

2016-11-22 10:32 UTC, chafique-delli commented
@pedrobaeza , see @alexis-via's comment of January 12  on the PR: https://github.com/OCA/multi-company/pull/13

2016-11-22 10:33 UTC, pedrobaeza commented
OK, I see the reasoning here: https://github.com/OCA/multi-company/pull/13#issuecomment-170832026

 @carlosdauden, what do you think?

2017-08-17 00:18 UTC, lasley commented
Hi @carlosdauden - any update on this?

2018-06-22 17:43 UTC, pedrobaeza commented
Closing as moving to v11

2018-06-22 17:43 UTC, closed without merging