[12.0][FIX] account_invoice_inter_company: do not write company_id on invoice lines
OCA/multi-company pull request #311
Opened 2021-09-03 07:29 UTC by AdriaGForgeFlow

The field company_id in the invoice.line model is a related readonly field that does not need to be written. Moreover, it causes Travis to fail when executing the tests.

cc ~ @ForgeFlow

2021-09-03 07:31 UTC, pedrobaeza requested changes
The field needs to be written because there are other fields that depends on it that are not correctly computed. The problem you mention should be by a view with higher priority that provokes to not select it correctly for the `Form`. Please check that instead.

2021-09-03 09:55 UTC, AdriaGForgeFlow commented
> The field needs to be written because there are other fields that depends on it that are not correctly computed. The problem you mention should be by a view with higher priority that provokes to not select it correctly for the `Form`. Please check that instead.

You are right. 
What do you think about the new solution, it's the only way I found but maybe you can think of a better approach. I tried working with priorities on the views but did not work.

2021-09-03 09:56 UTC, pedrobaeza commented
I don't think that's a good solution, but unless you put the steps to reproduce the problem, we can't provide alternatives.

2021-09-03 10:01 UTC, AdriaGForgeFlow commented
> I don't think that's a good solution, but unless you put the steps to reproduce the problem, we can't provide alternatives.

To reproduce the issue:
In a fresh Odoo instance, install the modules purchase_sale_inter_company and the module account_bill_line_distribution. You can then run the tests for purchase_sale_inter_company and you will have one FAILED test. Otherwise, you can configure the Odoo and create an inter-company invoice. When you try to post that invoice you will also see the issue in the logs complaining about writing in a field that is readonly.

2021-09-28 12:34 UTC, pedrobaeza commented
This fix #313 should be the solution for this (it needs to be back-ported though).

2021-09-29 08:25 UTC, AdriaGForgeFlow commented
> This fix #313 should be the solution for this (it needs to be back-ported though).

I have tried but it does not fix the issue, the code never enters that create / write and the inverse is already defined in v12.

2022-07-24 12:18 UTC, closed without merging