[14.0][UPD] account_invoice_inter_company_queued
OCA/multi-company pull request #372
Opened 2022-08-08 17:28 UTC by ilyasProgrammer

2022-08-11 16:32 UTC, elvise approved these changes
Functional review: Perfect!

2022-08-11 16:34 UTC, francesco-ooops approved these changes
functional review ok

2022-08-12 11:31 UTC, elvise commented
@pedrobaeza also this one looks ready :)

2022-08-12 11:58 UTC, pedrobaeza requested changes
You can't put such code in the main module. Please follow other approach like the one I used in https://github.com/OCA/bank-payment/tree/8.0/account_payment_transfer_reconcile_batch

2022-08-12 12:01 UTC, elvise commented
@ilyasProgrammer Can you follow the comment ?

2022-08-15 08:25 UTC, ilyasProgrammer commented
@pedrobaeza is it better now? I'm not sure if this exact change that was requested.

2022-08-15 09:10 UTC, pedrobaeza commented on account_invoice_inter_company/models/account_move.py
> +        if not self.env.context.get("queued"):
Use a more specific context key for avoiding conflicts and do the check here:

```suggestion
        if not self.env.context.get("account_invoice_inter_company_queued"):
```

2022-08-15 09:10 UTC, pedrobaeza commented on account_invoice_inter_company/views/res_config_settings_view.xml
> +                    <div class="col-12 col-lg-6 o_setting_box" id="invoice_queued">
Don't add this here, but on the new module. Name the div or group you need for hooking it correctly though.

2022-08-15 09:24 UTC, pedrobaeza commented on account_invoice_inter_company/models/res_config_settings.py
> +    module_account_invoice_inter_company_queued = fields.Boolean(
Please don't do that. When migrating modules, this option won't be available until the other module is migrated, and confuse users.

2022-08-15 09:29 UTC, pedrobaeza approved these changes

2022-08-15 09:29 UTC, pedrobaeza commented on account_invoice_inter_company_queued/views/res_config_settings_view.xml
> +                        <field name="module_account_invoice_inter_company_queued" />
This is like a self-destruction mechanism, hehe

2022-08-15 09:30 UTC, pedrobaeza commented
/ocabot merge nobump

2022-08-15 09:38 UTC, merged