[16.0][MIG] mail_multicompany: Migration to 16.0
OCA/multi-company pull request #479
Opened 2023-05-10 20:59 UTC by slitheryduke11

2023-05-11 17:12 UTC, desdelinux commented
/ocabot migrate mail_multicompany

2023-05-11 17:12 UTC, desdelinux commented
/ocabot migration mail_multicompany

2023-05-11 17:23 UTC, moylop260 commented
/ocabot migration mail_multicompany

2023-05-15 17:06 UTC, slitheryduke11 commented
Hi @luisg123v, @jesusVMayor, @Cedric-Pigeon, @ValentinVinagre. I think this migration is ready.

I would appreciate it if you could help me with the review.

Thanks in advance!

2023-05-15 17:27 UTC, ValentinVinagre commented
Hello @slitheryduke11 ,
we do not support this module because when it was ported to OCA changes were made to which we did not agree. We use the one from our public repository.

All the best,

2023-05-15 19:30 UTC, slitheryduke11 commented
@ValentinVinagre, I understand.

Thank you for the information.

2023-05-17 21:37 UTC, desdelinux commented
@dreispt @hugho-ad @moylop260 

could you review it please

2023-05-19 07:31 UTC, dreispt approved these changes

2023-05-20 15:45 UTC, luisg123v requested changes

2023-05-20 15:45 UTC, luisg123v commented on mail_multicompany/__manifest__.py
> +    "version": "16.0.0.1.0",
16.0.1.0.0

2023-05-20 15:45 UTC, luisg123v commented on mail_multicompany/tests/test_mail_multicompany.py
> +                "company_ids": [(4, cls.company1.id), (4, cls.company2.id)],
Use the Command syntax

2023-05-20 15:45 UTC, luisg123v commented on mail_multicompany/models/mail_message.py
> +    def create(self, values_list):
`vals_list`, to preserve original signature

2023-05-24 17:34 UTC, slitheryduke11 commented
Hi, @luisg123v. All suggestions done.

2023-05-25 19:43 UTC, luisg123v approved these changes
LGTM :+1: 

Hi @dreispt or @moylop260,

Could you merge, please?

2023-05-25 21:52 UTC, moylop260 commented
/ocabot merge nobump

2023-05-25 21:58 UTC, merged