[16.0][MIG] product_category_company_favorite (from 12.0)
OCA/multi-company pull request #549
Opened 2023-12-17 12:21 UTC by legalsylvain

2023-12-17 12:21 UTC, legalsylvain commented
/ocabot migration product_category_company_favorite

2023-12-17 14:30 UTC, legalsylvain commented
This one should be ready to review :

- CC : original reviewer of https://github.com/OCA/multi-company/pull/428 (@fcayre, @carmenbianca)

- CC : authors / reviewers of ``product_category_company`` that is a concurrent implementation. @ carmenbianca, @Kev-Roche, @cathLemb, @PaulGoubert

2023-12-17 15:54 UTC, rvalyi approved these changes
great module!

2024-01-26 10:11 UTC, quentinDupont requested changes
Otherwise, code lgtm and well tested :heavy_check_mark:

2024-01-26 10:11 UTC, quentinDupont commented on product_category_company_favorite/i18n/fr.po
> +msgstr "favorie"
```suggestion
msgstr "favorite"
```

2024-01-26 10:11 UTC, quentinDupont commented on product_category_company_favorite/i18n/fr.po
> +msgstr "favorie"
```suggestion
msgstr "favorites"
```

2024-02-20 13:24 UTC, legalsylvain commented
Thanks @quentinDupont. I fixed the translation.

/ocabot merge patch

2024-02-20 13:31 UTC, merged