[9.0][WIP] product_tax_multicompany_default: WIP
OCA/multi-company pull request #58
Opened 2017-07-21 10:15 UTC by carlosdauden

Set product taxes in all companies

@Tecnativa

2017-07-21 14:23 UTC, pedrobaeza requested changes

2017-07-21 14:23 UTC, pedrobaeza commented on product_tax_multicompany_default/README.rst
> +This modules set default taxes when product create and adds a button to set not
```
This module sets the default company taxes for all the existing companies when a product is created. It also adds a button to set all the taxes from other companies matching them by tax code.
```

2017-07-21 14:23 UTC, pedrobaeza commented on product_tax_multicompany_default/README.rst
> +
Add `Configuration` section:

#. As obvious, you need to have several companies.
#. Go to *Accounting > Configuration > Settings*
#. Select the proper company (if you are admin or a user with several companies access), or keep the current one (for a regular user).
#. On *Invoicing & Payments* section, set fields "Default Sale Tax" and "Default Purchase Tax".
```

2017-07-21 14:23 UTC, pedrobaeza commented on product_tax_multicompany_default/README.rst
> +#. Go to Sales > Sales > Products
```
#. Go to Sales > Sales > Products.
#. Create a new product and save it.
#. Switching user company (or being as admin or user with several companies access), you will see that the product has the default taxes for all the companies.
```

2017-07-21 14:23 UTC, pedrobaeza commented on product_tax_multicompany_default/__openerp__.py
> +        This modules set default taxes when product create and adds
Remove this summary or put it correctly (and in a summarized way)

2017-07-21 14:23 UTC, pedrobaeza commented on product_tax_multicompany_default/__openerp__.py
> +    'website': 'http://www.tecnativa.com',
https

2017-07-21 14:23 UTC, pedrobaeza commented on product_tax_multicompany_default/__openerp__.py
> +        'product',
This is clearly depending on `account`

2017-07-21 14:23 UTC, pedrobaeza commented on product_tax_multicompany_default/models/product_template.py
> +
Don't put empty line breaks

2017-07-21 14:23 UTC, pedrobaeza commented on product_tax_multicompany_default/models/product_template.py
> +        tax_ids = self.taxes_id.ids
customer_tax_ids?

2017-07-21 14:23 UTC, pedrobaeza commented on product_tax_multicompany_default/models/product_template.py
> +        default_taxes = self.taxes_by_company('taxes_id', company_id)
If these are a list of IDs, call it `default_tax_ids`, or better `default_customer_tax_ids`

2017-07-21 21:56 UTC, sergiocorato commented
Hi,
I tried this mp, but in a running installation it doesn't work, perhaps I missed something
It work if I change as of https://github.com/Tecnativa/multi-company/pull/1

2017-07-23 22:07 UTC, carlosdauden commented
Thanks for your reviews.

@sergiocorato, can you try after fix?

2017-07-26 07:43 UTC, carlosdauden commented
I can't reproduce travis errors in local tests.

2017-07-25 00:18:38,084 12154 ERROR openerp_test openerp.addons.product_tax_multicompany_default.tests.test_product_tax_multicompany: ` AccessError: ('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: product.template, Operation: read)', None)

Any problem with sudo(user) for travis?

2017-07-31 08:31 UTC, sergiocorato commented
@carlosdauden: now it works, well done!
:+1:

2017-08-16 16:59 UTC, pedrobaeza approved these changes
Tests fixed. They failed because of module product_multi_company installed alongside. Setting explicitly `company_id=False` in the values you overpass the problem.

2017-08-16 17:37 UTC, merged