[ADD] sale_stock_partner_warehouse
OCA/multi-company pull request #581
Opened 2024-01-31 13:40 UTC by santostelmo

### Description
Allow to choose by default a warehouse on SO based on a Partner parameter. 
If the warehouse parameter is completed, then this value would be the default one on the sale. 
If empty, then the warehouse on sale would be the standard default warehouse.

2024-02-01 09:53 UTC, jbaudoux requested changes
This module is not related to multi-company and must move to sale-workflow repo

2024-02-01 09:53 UTC, jbaudoux commented on sale_stock_partner_warehouse/__manifest__.py
> +        "sale_stock_warehouse_multicompany",
You don't need this dependency
```suggestion
```

2024-02-01 09:53 UTC, jbaudoux commented on sale_stock_partner_warehouse/models/sale_order.py
> +    @api.depends("user_id", "company_id", "partner_id.sale_warehouse_id")
If you change the wh on the partner, you probably don't want to recompute all SO of that partner
```suggestion
    @api.depends("user_id", "company_id", "partner_id")
```

2024-02-01 10:25 UTC, santostelmo commented on sale_stock_partner_warehouse/__manifest__.py
> +        "sale_stock_warehouse_multicompany",
Removed dependency

2024-03-26 12:48 UTC, santostelmo commented
> This module is not related to multi-company and must move to sale-workflow repo

Moving it to sale-workflow: https://github.com/OCA/sale-workflow/pull/3044

2024-03-26 13:34 UTC, santostelmo commented
@jbaudoux can you plase check the PR on OCA sale-workflow ?

2024-03-26 13:34 UTC, closed without merging