[16.0][IMP] x_x_multicompany_default context flag to force on write
OCA/multi-company pull request #638
Opened 2024-06-12 08:19 UTC by yvaucher

Following #627 

(only last commit is relevent)

Add the possibility to propagate properties on write if a context key is set.
This can be useful in case of data import

2024-06-20 06:23 UTC, santostelmo approved these changes

2024-06-28 06:06 UTC, cyrilmanuel approved these changes
not an expert but LGTM

2024-06-28 06:24 UTC, santostelmo commented
@yajo it's okay for you ?

2024-07-01 06:49 UTC, cyrilmanuel commented
Hello @pedrobaeza, could you merge this PR ?

2024-07-01 14:21 UTC, pedrobaeza commented
You should rebase when #627 is merged.

2025-01-23 14:21 UTC, santostelmo commented
@pedrobaeza could you please reopen this PR ?

2025-02-20 17:28 UTC, legalsylvain requested changes
CI is red.

also maintainer approval is required for such big changes.

(new dependency).

thanks !

2025-07-23 13:33 UTC, closed without merging