[FIX] purchase_sale_stock_inter_company: default warehouse from same …
OCA/multi-company pull request #655
Opened 2024-07-03 11:15 UTC by cyrilmanuel

…partner_id

2024-07-03 15:26 UTC, jbaudoux requested changes
LG, just a small remark

2024-07-03 15:26 UTC, jbaudoux commented on purchase_sale_stock_inter_company/models/purchase_order.py
> +        )
To prevent singleton error:
```suggestion
        limit=1)
```

2024-07-03 15:32 UTC, jbaudoux requested changes

2024-07-03 15:32 UTC, jbaudoux commented on purchase_sale_stock_inter_company/models/purchase_order.py
> +            [("partner_id", "=", self.partner_id.id)]
You forgot the last part of your PR description (belongs to dest company)
```suggestion
            [
            ("partner_id", "=", self.partner_id.id),
            ("company_id", "=", dest_company.id),
            ]
```

2024-07-03 15:38 UTC, jbaudoux reviewed
Can you add the unit test for the case you are fixing?

2024-11-04 08:58 UTC, jbaudoux commented
@cyrilmanuel Where do you stand with this fix? Would be nice to integrate it

2025-05-11 12:22 UTC, closed without merging

2026-02-18 08:56 UTC, cyrilmanuel commented
superseeded at https://github.com/OCA/multi-company/pull/948