16.0 mig crm stage multi company
OCA/multi-company pull request #666
Opened 2024-07-16 08:24 UTC by julienCozo

Migration to 16.0

2024-07-16 09:35 UTC, remi-filament requested changes
Thank you @julienCozo 
you should rename this PR to : "[16.0][MIG] crm_stage_multi_company: Migration to 16.0"
Also, please fix failing tests from this module.

2024-07-16 13:57 UTC, remi-filament commented
Hi @julienCozo thanks for fixing the tests, you should still :

- [x] update name of PR
- [x] squash your 4 commits into 1 (or max 2 : pre-commit + migration)

2024-07-30 08:55 UTC, theo-le-filament approved these changes

2024-08-01 15:35 UTC, remi-filament approved these changes
Tested OK

2025-01-31 09:27 UTC, JordiMForgeFlow commented
@julienCozo could you fix the migration commits and rebase?

2025-02-20 17:29 UTC, closed without merging