[18.0][MIG] web_field_company_dependent_flag: Migration to 18.0
OCA/multi-company pull request #709
Opened 2024-10-23 12:34 UTC by BertVGroenendael

2025-04-30 15:35 UTC, bealdav commented
Just tested, works as expected. Thanks a lot @BertVGroenendael 
Please reopen This PR ready to be mergeable (maybe squash `[IMP] company_dependent_flag` last commit)

2025-04-30 15:36 UTC, bealdav reviewed
Thanks a lot

2025-04-30 16:05 UTC, bealdav approved these changes

2025-05-01 12:04 UTC, legalsylvain commented on web_field_company_dependent_flag/__init__.py
> +    from . import demo
I' m not sure adding demo python file is a good thing. I think we could use the classic odoo_test_helper tools.
See for exemple : 
- https://github.com/OCA/server-tools/blob/18.0/base_exception/tests/test_base_exception.py#L5
- https://github.com/OCA/server-tools/blob/18.0/base_time_window/tests/test_time_window_mixin.py#L1
- https://github.com/OCA/stock-logistics-barcode/blob/16.0/barcodes_generator_abstract/tests/test_barcodes_generator_abstract.py#L4

2025-05-01 12:07 UTC, legalsylvain commented on web_field_company_dependent_flag/readme/ROADMAP.md
> +  web_field_company_dependent_flag
This file can be removed.

2025-05-01 12:07 UTC, legalsylvain reviewed
a remark inline. Otherwise, LGTM.  thanks ! 

could you make a PR against OCA/openupgrade repo, regarding the renaming ? 
https://github.com/OCA/OpenUpgrade/blob/18.0/openupgrade_scripts/apriori.py

2025-05-06 13:34 UTC, PaulGoubert approved these changes
Functional review: OK. Useful in a multi-company context.  Thanks

2025-06-13 09:47 UTC, legalsylvain commented
/ocabot migration company_dependent_flag

2025-06-18 20:07 UTC, legalsylvain commented
/ocabot migration company_dependent_flag

2025-08-21 14:04 UTC, LoisRForgeFlow commented
@BertVGroenendael Just a kind reminder that there are comments from @legalsylvain pending to attend.

2025-10-01 08:41 UTC, bealdav commented
Done here
https://github.com/OCA/OpenUpgrade/pull/5390/files

2026-02-03 14:05 UTC, sergiocorato requested changes

2026-02-03 14:05 UTC, sergiocorato commented on web_field_company_dependent_flag/hooks.py
> +def pre_init_partner_phone(env):
It seems like a commit from another module?
I don't understand why this code is in this module.

2026-06-23 10:20 UTC, lmarion-source approved these changes

2026-06-23 10:21 UTC, lmarion-source commented
@BertVGroenendael  could you review the comment from @legalsylvain  then ask for the merge of this PR ? 

Code LGTM otherwise.

Thanks

2026-09-03 15:22 UTC, legalsylvain commented
superseded by https://github.com/OCA/multi-company/pull/1052

2026-09-03 15:22 UTC, closed without merging