[10.0][MIG] account_type_multi_company
OCA/multi-company pull request #73
Opened 2017-11-12 19:22 UTC by luc-demeyer

2017-11-13 01:16 UTC, elicoidal requested changes
Some details. Other than that LGTM

2017-11-13 01:16 UTC, elicoidal commented on account_type_multi_company/README.rst
> +.. image:: https://img.shields.io/badge/license-AGPL--3-blue.svg
better use png image following new standards

2017-11-13 01:16 UTC, elicoidal commented on account_type_multi_company/README.rst
> +This module makes the account types multi company aware.
multi-company

2017-11-13 01:16 UTC, elicoidal commented on account_type_multi_company/README.rst
> +Both modules can downloaded from git, cf. https://github.com/OCA/account-financial-tools/tree/10.0
can be

2017-11-13 12:45 UTC, luc-demeyer commented
@elicoidal 
Thanks for the review.
I have fixed the typos.
Changing the svg to png doesn't seem a good idea since
https://img.shields.io/badge/license-AGPL--3-blue.png
does not exist.

2017-11-14 01:08 UTC, elicoidal commented
@luc-demeyer are you sure? on my side there is an output.
![screenshot from 2017-11-14 09-05-32](https://user-images.githubusercontent.com/7600613/32757594-3ab878ee-c91b-11e7-863a-44f812254efa.png)

and wget works fine.

Is there something I am missing

FYI: we removed the svg because it is not rendered properly in the Odoo apps platform

2017-11-14 08:19 UTC, luc-demeyer commented
@elicoidal 
strange but now the png renders fine effectively.
I have updated the PR.

2017-11-14 09:59 UTC, elicoidal approved these changes

2017-12-14 21:21 UTC, lasley approved these changes

2017-12-14 21:22 UTC, merged

2017-12-14 21:22 UTC, lasley commented
Thanks @luc-demeyer