[18.0][MIG] mail_multicompany: Migration to 18.0
OCA/multi-company pull request #748
Opened 2024-12-23 12:31 UTC by HeliconiaSolutions

2025-02-20 15:10 UTC, legalsylvain commented
/ocabot migration mail_multicompany

2025-06-11 22:16 UTC, isaako34 commented
LGTM

2025-06-11 22:16 UTC, isaako34 approved these changes

2025-06-26 19:19 UTC, luisg123v requested changes
Just missing #799 in the history.

2025-07-14 15:16 UTC, ByteMeAsap commented
@BhaveshHeliconia , can you add in the commit as suggested by @luisg123v

2025-07-15 12:36 UTC, BhaveshHeliconia commented
@luisg123v @ByteMeAsap Just to confirm, as these are changes in the migration folder, should we also include them in the 18.0 migration?

2025-07-15 15:37 UTC, luisg123v commented
@BhaveshHeliconia no, migration scripts will be removed anyway, but it's important to preserve history whenever possible.

2025-07-22 19:22 UTC, luisg123v commented
Hi @BhaveshHeliconia,

Just missing that small change to merge.

Could you perform it, please?

2025-07-23 19:24 UTC, luisg123v commented
/ocabot merge nobump

2025-07-23 19:29 UTC, merged

2025-07-23 19:44 UTC, luisg123v commented
Merging since the author is unavailable and the missing commit does not affect the result in any way.