[18.0][MIG] res_company_search_view: Migration to 18.0
OCA/multi-company pull request #751
Opened 2024-12-26 11:18 UTC by HeliconiaSolutions

2025-01-24 13:28 UTC, amh-mw requested changes

2025-01-24 13:28 UTC, amh-mw commented on res_company_search_view/models/res_company.py
> +    state_id = fields.Many2one(store=True)
Why are these model changes necessary? Aren't these values stored on the related partner_id?

2025-01-27 11:37 UTC, Christian-RB commented on res_company_search_view/models/res_company.py
> +    state_id = fields.Many2one(store=True)
I think the same as @amh-mw, is there any reason to add this @HeliconiaSolutions?

2025-01-31 11:53 UTC, HeliconiaSolutions commented on res_company_search_view/models/res_company.py
> +    state_id = fields.Many2one(store=True)
@Christian-RB , @amh-mw , Thank you for suggestions! It's fixed Please review.

2025-01-31 13:09 UTC, amh-mw approved these changes
Code review only. LGTM.

2025-02-04 12:53 UTC, Christian-RB requested changes
Almost there just one last thing

2025-02-04 12:53 UTC, Christian-RB commented on res_company_search_view/tests/test_res_company.py
> +class TestResCompany(TransactionCase):
Sorry just saw this on https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0

> Use BaseCommon as base test class to reduce overhead from tracking and boost the test suite.

```suggestion
from odoo.addons.base.tests.common import BaseCommon


class TestResCompany(BaseCommon):
```

2025-02-07 11:15 UTC, BhaveshHeliconia commented on res_company_search_view/tests/test_res_company.py
> +class TestResCompany(TransactionCase):
@Christian-RB yes! it's Fixed.please review.

2025-02-11 12:22 UTC, Christian-RB approved these changes

2025-02-20 12:05 UTC, BhaveshHeliconia commented
@legalsylvain , Can you please proceed with merging this PR?

2025-02-20 14:30 UTC, legalsylvain requested changes

2025-02-20 14:30 UTC, legalsylvain commented on res_company_search_view/tests/test_res_company.py
> +from odoo.addons.base.tests.common import BaseCommon
Hi.

I don't understand that file. I see the tests quite unrelated to the addition of the search view.

2025-02-20 14:32 UTC, legalsylvain commented
/ocabot migration res_company_search_view

2025-02-20 14:34 UTC, legalsylvain commented
/ocabot migration res_company_search_view

2025-02-21 04:26 UTC, HeliconiaSolutions commented on res_company_search_view/tests/test_res_company.py
> +from odoo.addons.base.tests.common import BaseCommon
@legalsylvain, These changes were added to fix failing CI/CD test cases. If they are no longer needed, I can remove them.

2025-02-21 08:16 UTC, legalsylvain commented on res_company_search_view/tests/test_res_company.py
> +from odoo.addons.base.tests.common import BaseCommon
Yes. I guess you can remove the whole ``tests`` folder.

2025-02-21 08:51 UTC, HeliconiaSolutions commented on res_company_search_view/tests/test_res_company.py
> +from odoo.addons.base.tests.common import BaseCommon
@legalsylvain , Please review. i removed tests folder.

2025-02-21 08:54 UTC, legalsylvain reviewed
Diff review. https://github.com/OCA/multi-company/pull/751/commits/56dd4914566a919d5366cdd06cd4ef264d166317

LGTM.

/ocabot merge nobump

2025-02-21 08:58 UTC, merged