[MIG] product_tax_multicompany_default: Migration to 11.0
OCA/multi-company pull request #98
Opened 2018-05-08 16:06 UTC by cubells

- Update README
- Update tests

cc @Tecnativa

2018-05-09 19:59 UTC, pedrobaeza requested changes

2018-05-09 19:59 UTC, pedrobaeza commented on product_tax_multicompany_default/tests/test_product_tax_multicompany.py
>  from openerp.tests.common import SavepointCase
s/openerp/odoo

2018-05-09 19:59 UTC, pedrobaeza commented on product_tax_multicompany_default/views/product_template_view.xml
> +                <button name="set_multicompany_taxes"
Incorrect indentation + align also rest of attributes names

2018-05-11 15:35 UTC, cubells commented
@pedrobaeza can you recheck this?

2018-05-19 18:19 UTC, pedrobaeza approved these changes

2018-05-21 10:13 UTC, carlosdauden approved these changes

2018-06-13 15:10 UTC, oihane commented on product_tax_multicompany_default/models/product.py
> +# -*- coding: utf-8 -*-
The first line # -*- coding: utf-8 -*- is not needed anymore in Python 3

2018-06-13 15:10 UTC, oihane commented on product_tax_multicompany_default/tests/test_product_tax_multicompany.py
> +# -*- coding: utf-8 -*-
It's not needed

2018-06-13 15:14 UTC, cubells commented
@oihane done!

2018-06-13 15:21 UTC, oihane approved these changes
Perfect, technically reviewed

2018-06-15 10:24 UTC, carlosdauden approved these changes

2018-06-21 16:55 UTC, merged